<a href="https://colab.research.google.com/github/ashwinamrutphale/aml-homeworks/blob/master/homework2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn import datasets
from sklearn import preprocessing

In [0]:
def soft_threshold(b,lamda):
#     print(b)
#     print(lamda)
    if b < -(lamda/2.):
        return (b + lamda/2.)
    elif b >  lamda/2.:
        return (b - lamda/2.)
    else: 
        return 0

In [0]:
def coordinate_loop(X_l,y_l,lamda,beta_l):
  m,n = X_l.shape
  for j in range(n):
    #Vectorized implementation
    X_j = X_l[:,j].reshape(-1,1)
    y_pred = X_l @ beta_l
    #print(y_pred)
    rho = (X_j*(y - y_pred  + beta_l[j]*X_j)).sum()
    #print(rho)
    beta_l[j] =  soft_threshold(rho, lamda)
    #print(beta[j])
  return beta_l
  
  

In [0]:
def my_lasso(X,y,lamda, num_iters,tol):
    #Initialisation of useful values
    m,n = X.shape
    beta_new = np.zeros(n)
    beta_old = beta_new
    
    
    #Looping until max number of iterations
    for i in range(num_iters):
      beta_new = np.reshape(coordinate_loop(X,y,lamda,beta_old),(200,1))
      l1 = np.linalg.norm(beta_new-beta_old,ord=1)
      print(l1)
      if(l1 < tol):
        print("converged after iteration {}".format(str(i)))
        break
      beta_new = beta_old
            
    return beta_new.flatten()

In [11]:
n = 200
p = 200
V = np.full((p, p), 0.2)
np.fill_diagonal(V, 1)
X = np.random.multivariate_normal(np.zeros(p), V, n)

array([[ 3.36080314e-01,  9.93269673e-02, -6.20741268e-01, ...,
        -1.15890054e+00, -9.75029143e-02,  1.46735278e-01],
       [ 5.77983426e-02, -8.79981966e-01, -9.50960230e-01, ...,
        -2.92228454e-01,  1.62156308e+00, -2.13186700e-01],
       [-1.37475259e+00,  4.36936893e-01, -1.04300872e+00, ...,
        -2.19462846e-01, -8.04087680e-01, -9.88256317e-01],
       ...,
       [ 3.13657627e-01,  1.05992938e+00,  5.52497552e-01, ...,
         5.24544294e-01,  2.87901046e-01,  3.30516751e-03],
       [-1.19468380e+00,  1.67546235e+00,  8.22907715e-01, ...,
         2.80705229e-01,  1.06276947e+00,  3.17043812e-01],
       [-1.28564919e+00, -1.98888770e+00,  5.56254056e-01, ...,
        -2.27651330e-01, -8.55250763e-01, -3.51609316e+00]])

In [0]:
np.random.seed(1)
eta = np.random.randn(n)
ly = lambda x : x[1] + 0.5*x[2] + 0.25*x[3]
#Vectorized add of eta
y = np.add(np.apply_along_axis(ly,1,X),eta)


In [114]:
y = np.reshape(y,(200,1))
y.shape



(200, 1)

In [121]:
X_scaled = X/np.linalg.norm(X, axis=0)
y_scaled = y/np.linalg.norm(y, axis=0)
#d = my_lasso(X,y,0.3,100,1e-5)
#np.linalg.norm(d-)

X_scaled
#y_scaled


array([[ 0.02260962,  0.00563522, -0.04461544, ..., -0.08438355,
        -0.00787133,  0.00558534],
       [ 0.00322816, -0.05872278, -0.0674739 , ..., -0.02284928,
         0.12618102, -0.02034739],
       [-0.09654449,  0.02782219, -0.07384569, ..., -0.01768288,
        -0.06297063, -0.07619192],
       ...,
       [ 0.02104795,  0.06876386,  0.03659863, ...,  0.0351421 ,
         0.02218238, -0.00474894],
       [-0.08400327,  0.10921532,  0.055317  , ...,  0.01782937,
         0.08260643,  0.01785623],
       [-0.09033872, -0.13159759,  0.03685866, ..., -0.01826427,
        -0.06696032, -0.25832503]])

In [137]:
coordinate_loop(X_scaled,y_scaled,0.3,np.zeros((n,1)))
#d = my_lasso(X_scaled,y_scaled,0.3,100,1e-5)

array([[ 3.13174510e+00],
       [ 1.38676134e+01],
       [ 5.55772263e+00],
       [ 2.30882135e+00],
       [-6.03375570e-02],
       [ 1.12837201e+00],
       [-1.03366419e+00],
       [ 0.00000000e+00],
       [ 1.37453244e-01],
       [-1.68759597e+00],
       [-2.39050553e-01],
       [ 6.61863422e-01],
       [ 1.26300196e+00],
       [ 0.00000000e+00],
       [ 7.08405456e-01],
       [-9.39171733e-01],
       [-1.89053718e-01],
       [-1.74201368e+00],
       [ 9.90637575e-01],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 4.12939374e-02],
       [-8.62611456e-02],
       [-8.74588999e-01],
       [ 0.00000000e+00],
       [-3.62006338e-01],
       [ 1.03279566e+00],
       [ 7.07154167e-01],
       [-1.86756982e+00],
       [ 1.35506872e-01],
       [ 5.13995216e-01],
       [ 1.05920753e+00],
       [ 1.56579016e-01],
       [ 8.15817234e-01],
       [-8.71692052e-01],
       [-3.99872199e-01],
       [-5.35402696e-01],
       [-6.24072801e-01],
       [ 1.4

In [0]:
from sklearn import linear_model
clf = linear_model.Lasso(alpha=0.3)
clf.fit(X,y)
print(clf.coef_)

In [129]:
d

array([2.01920031e+229, 8.98551267e+229, 5.37037858e+229, 4.84456804e+229,
       2.24377294e+229, 3.92425273e+229, 2.40994425e+229, 4.04948074e+229,
       2.90128932e+229, 2.11095120e+229, 2.56024788e+229, 3.33448087e+229,
       2.95640735e+229, 2.97982422e+229, 1.85691459e+229, 2.52222662e+229,
       1.08730913e+229, 1.91092940e+229, 3.27109897e+229, 2.54567560e+229,
       2.72377942e+229, 2.11292555e+229, 3.22900833e+229, 3.22066253e+229,
       1.45841813e+229, 2.11491826e+229, 3.70476831e+229, 3.05258953e+229,
       1.37435097e+229, 3.20394617e+229, 3.56246655e+229, 2.01533882e+229,
       3.10088786e+229, 1.64504725e+229, 1.24575773e+229, 2.19529542e+229,
       2.01254577e+229, 2.10523882e+229, 3.39999243e+229, 2.30263460e+229,
       3.36905908e+229, 3.26954852e+229, 2.45836931e+229, 3.27944548e+229,
       2.92248556e+229, 1.74705918e+229, 2.17734461e+229, 1.90716465e+229,
       2.60927571e+229, 1.54957207e+229, 2.13008183e+229, 2.62519815e+229,
       2.92846300e+229, 1